export const data = [
  {
    NP: '001',
    Name: 'Sylva madu',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Nigeria',
    Earnings: '$203.45',
    rate: '1',
  },
  {
    NP: '002',
    Name: 'John Doe',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Kenya',
    Earnings: '$203.45',
    rate: '4',
  },
  {
    NP: '003',
    Name: 'favor luke',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Romiania',
    Earnings: '$203.45',
    rate: '2',
  },
  {
    NP: '004',
    Name: 'Helen osuji',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Nigeria',
    Earnings: '$203.45',
    rate: '3',
  },
  {
    NP: '005',
    Name: 'Sylva madu',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Nigeria',
    Earnings: '$203.45',
    rate: '5',
  },
  {
    NP: '006',
    Name: 'John Doe',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Kenya',
    Earnings: '$203.45',
    rate: '4',
  },
  {
    NP: '007',
    Name: 'favor luke',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Romiania',
    Earnings: '$203.45',
    rate: '2',
  },
  {
    NP: '008',
    Name: 'Helen osuji',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Nigeria',
    Earnings: '$203.45',
    rate: '3',
  },
  {
    NP: '009',
    Name: 'favor luke',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Romiania',
    Earnings: '$203.45',
    rate: '2',
  },
  {
    NP: '010',
    Name: 'Helen osuji',
    "Portfolio Link": 'www.github.com/sylvamadu',
    "country": 'Nigeria',
    Earnings: '$203.45',
    rate: '3',
  },
]